name: Workflow memory

on:
  push:
    branches:
      - develop

jobs:
  test-memory:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Test JPG files
      run: |
        for file in $(find . -name "*.jpg"); do
          result=$(file "$file")

          if [[ "$result" != *"JPEG image data"* ]]; then
            echo "$file est corrompu, remplacement..."
            cp ~/image.jpg "$file"  # Remplacer par une image valide
          else
            echo "$file est valide."
          fi
        done

    - name: Commit changes if any
      run: |
        git config --global user.name 'JWarconsin'
        git config --global user.email 'jeremie.warconsin@student.junia.com'

        if git diff --quiet; then
          echo "Aucune modification détectée."
        else
          git add .
          git commit -m "Remplacement des fichiers jpg corrompus"
          git push origin develop  # Pousser les changements sur la branche develop
        fi

  build-memory:
    runs-on: self-hosted
    needs: test-memory

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Build image docker
        run: docker build -t jeremiewarconsin/memory .  # Utiliser le secret pour le nom d'utilisateur

  push-memory:
    runs-on: self-hosted
    needs: build-memory

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Push image docker dans docker hub
        run: docker push jeremiewarconsin/memory  # Pousser l'image Docker

  deploy-memory:
    runs-on: self-hosted
    needs: push-memory # Le job deploy-memory ne s'exécute qu'après push-me>

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Pull Docker images and start containers
        run: |
          if [ "$(docker ps -q -f name=memory-container)" ]; then
              echo "Container 'memory' is running. Stopping and removing it>
              docker stop memory-container
          else
              echo "Container 'memory' is not running."
          fi
          if [ "$(docker ps -q -a -f name=memory-container)" ]; then
            docker rm memory-container
          fi
          ssh ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} << 'EOF'          docker pull yoyo338/memory
          docker run -d --name memory-container -p 80:80 yoyo338/memory
          EOF
