name: CI

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: self-hosted  # S'assurer que le runner est self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          docker build -t orewaprogramaninaru/memory .

      - name: Run Docker container
        run: |
          docker run -d -p 3000:80 orewaprogramaninaru/memory
