name: CI Workflow

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: self-hosted  # Utiliser le runner auto-hébergé
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Remplace par la version de Node.js souhaitée

      - name: Install dependencies
        run: npm install  # Installer les dépendances si nécessaire

      - name: Build project
        run: npm run build  # Remplace par la commande de build de ton projet

      - name: Run tests
        run: npm test  # Exécuter les tests
